Aname: "HA-OAuthPassThru"
version: "1.1.0"
slug: "HA-OAuthPassThru"
description: >-
  "Just a server to simply allow apps to OAuth and use Home Assist Login while providing user logins" 
arch:
  - amd64
url: "https://github.com/Soy-HA/HA-OauthPassThru/README.md"
ports:
  2010/tcp: 2010
auth_api:
websocket_api:
startup: services
